name: Deployment to GitHub Pages
on:
  push:
    branches: [ master ]
env:
  ROADMAP_GA_SECRET: ${{ secrets.GA_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup Environment
      run: |
        npm install -g yarn
        yarn install
    - name: Generate meta and builld
      run: |
        yarn meta
        yarn build
    - name: Deploy to GitHub Pages
      run: |
        git config user.email "kamranahmed.se@gmail.com"
        git config user.name "Kamran Ahmed"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy
